### PR TITLE
Modify how command line arguments are parsed.

### LINKED ISSUE #30: argparse
use [argparse](https://docs.python.org/3/library/argparse.html) to parse arguments

currently, we must set options first

```
subdl --option movie.mkv
```

but this should work too

```
subdl movie.mkv --option
```

### PR DESCRIPTION
**Pull request by FranciscoRomao**
The arguments are now parsed using the argparse library. Fix #30

### CODE REVIEW

**Comment by milahu** [comment]
please squash commits

`git rebase` would require solving conflicts, so this is easier:

```
cp subdl.py subdl.py.bak
git branch argparse-bak
git reset --hard origin/master

black subdl.py
git add subdl.py
git commit -m "format with black"

cp subdl.py.bak subdl.py
git add subdl.py
git commit -m "use argparse to parse arguments" 

git push --force
```

on further changes

```
git add subdl.py
git commit --amend
git push --force
```

other than that ...

dont use `global options`. instead use `return options`

convert more `elif` branches to `if`. `raise SystemExit` will stop the program, so `elif` makes no sense after  `raise SystemExit`

inline `def default_output_fmt()` like before (called only once)

remove `import pdb`

remove `print("Available languages:")`

empty line before+after `options = parser.parse_args()`

**Comment by FranciscoRomao** [comment]
Thank you for all the helpful notes.
About using `return options` instead of global. In that case I will need to pass the `options` object to all the functions that use the object.

**Comment by FranciscoRomao** [comment]
Got it. Merged the pull request. Why do you prefer to have the available languages hardcoded on the script than in a separate file?

**Comment by milahu** [comment]
please squash commits, see https://github.com/FranciscoRomao/subdl/pull/1

using LANGUAGES in subdl.py is a micro optimization: avoid open+read+parse of text file

**Comment by FranciscoRomao** [comment]
Ok, I think that is it.

**Comment by milahu** [comment]
too many changes in e01c13eff070bf7dae6753c33c6698ce460075ad
in https://github.com/FranciscoRomao/subdl/pull/1 i suggested to create 6 commits (p = pick, f = fixup)

with that, we just need to wait for @alexanderwink ...

**Pull request merged**
